
export enum INNOVATIONS_ACTION_TYPES {
    READ_INNOVATION_START="innovation/READ_INNOVATION_START",
    READ_INNOVATION_FAILURE="innovation/READ_INNOVATION_FAILURE",
    READ_INNOVATION_SUCCESS="innovation/READ_INNOVATION_SUCCESS",
    
    LIKE_INNOVATION_START="innovation/LIKE_INNOVATION_START",
    LIKE_INNOVATION_FAILURE="innovation/LIKE_INNOVATION_FAILURE",
    LIKE_INNOVATION_SUCCESS="innovation/LIKE_INNOVATION_SUCCESS",
    
    UNLIKE_INNOVATION_START="innovation/UNLIKE_INNOVATION_START",
    UNLIKE_INNOVATION_FAILURE="innovation/UNLIKE_INNOVATION_FAILURE",
    UNLIKE_INNOVATION_SUCCESS="innovation/UNLIKE_INNOVATION_SUCCESS",
}
