
export enum CATEGORIES_ACTION_TYPES {

    CREATE_CATEGORY_START="categories/CREATE_CATEGORY_START",
    CREATE_CATEGORY_FAILURE="categories/CREATE_CATEGORY_FAILURE",
    CREATE_CATEGORY_SUCCESS="categories/CREATE_CATEGORY_SUCCESS",

    DELETE_CATEGORY_START="categories/DELETE_CATEGORY_START",
    DELETE_CATEGORY_FAILURE="categories/DELETE_CATEGORY_FAILURE",
    DELETE_CATEGORY_SUCCESS="categories/DELETE_CATEGORY_SUCCESS",
    
    UPDATE_CATEGORY_START="categories/UPDATE_CATEGORY_START",
    UPDATE_CATEGORY_FAILURE="categories/UPDATE_CATEGORY_FAILURE",
    UPDATE_CATEGORY_SUCCESS="categories/UPDATE_CATEGORY_SUCCESS",

    FETCH_CATEGORIES_START = "categories/FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_FAILURE = "categories/FETCH_CATEGORIES_FAILURE",
    FETCH_CATEGORIES_SUCCESS = "categories/FETCH_CATEGORIES_SUCCESS",
}